package vmprotect

import (
	"testing"
)

func TestTooShort(t *testing.T) {
	serial := "aGVsbG8sIHdvcmxk"
	_, err := ParseLicense(serial, vmpPublic, vmpModulus, vmpProductCode, vmpBits)
	if err == nil {
		t.Fatal("The input is too short, it must be invalid")
	}
}

func TestTooLong(t *testing.T) {
	serial := "aGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCBoZWxsbywgd29ybGQgaGVsbG8sIHdvcmxkIGhlbGxvLCB3b3JsZCA="
	_, err := ParseLicense(serial, vmpPublic, vmpModulus, vmpProductCode, vmpBits)
	if err == nil {
		t.Fatal("The input is too long, it must be invalid")
	}
}

func TestRightLength(t *testing.T) {
	serial := "RxtFJ+i0xRj8KNoyR9oAfQtOEHNRTKL5t/kWW7f/l0HFt9MC0uOhy0TeVC40LSjixdZ3xbON69bzloRDaAVyZMk44VPfT5jYt5PYyVEsZsWg1xkMdBNd1J2yrzI5cl8Ly2/w4JqZcJai7ubQDEz9MsTE1dfaoYT+vEnO4AjG+ynXYpZKQbIUAfDMBORR9KuVZp5wIJEFsloKZibU+W/72XLva5kSdXXGbtYIvKG8x41sO897aXBpVYbZ+WpnbGs7O3AqBhw0PNtJ2WAfN4Ce/RW0AkPDpfk4uqd5wvER5l9RNZnDjIhN1+/4dfmF1PMeFPaqhEcH3vf4SzJcfd6P4g=="
	_, err := ParseLicense(serial, vmpPublic, vmpModulus, vmpProductCode, vmpBits)
	if err == nil {
		t.Fatal("The input is of a right length, but still invalid")
	}
}

func TestSpacesAndNewLines(t *testing.T) {
	serial := "RxtFJ+i0xRj8KN\noyR9oAfQtOEHNRTKL5t/kWW7f/l0HFt9MC0u Ohy0TeVC40LSjixdZ3xbON69bzloRDaAVyZMk   44VPfT5jYt5PYyVEsZsWg1xkMdBNd1J2yrzI5cl8Ly2/w4JqZcJai\n\n\n7ubQDEz9MsTE1dfaoYT+vEnO4AjG+ynX\r\nYpZKQ\n\rbIUAfDMBORR9KuVZp5wIJEFsloKZibU+W/72XLva5kSdXXGbtYIvKG8x41sO897aXBpVYbZ+WpnbGs7O3AqBhw0PNtJ2WAfN4Ce/RW0AkPDpfk4uqd5wvER5l9RNZnDjIhN1+/4dfmF1PMeFPaqhEcH3vf4SzJcfd6P4g=="
	_, err := ParseLicense(serial, vmpPublic, vmpModulus, vmpProductCode, vmpBits)
	if err == nil {
		t.Fatal("The input is right just has some newlines and spaces, but still invalid")
	}
}

func TestIgnoreUnsupportedCharacters(t *testing.T) {
	serial := "RxtFJ+i0xRj8KNoyR9oAfQtOEHNRTKL5t/kWW7f/l0HFt9MC0uOhy0TeVC40LSjixdZ3xbO$$$N69bzloRDaAVyZMk44VPfT5jYt5PYyVEsZs---Wg1xkMdBNd1J2yrzI5cl8Ly2/w4JqZcJai7ubQDEz9MsT###E1dfaoYT+vEnO4AjG+ynXYpZKQbIUAfDMBORR9KuVZp5wIJEFsloKZibU+W/72XLva5kSdXXGbtYIvKG8x41sO897aXBpVYbZ+WpnbGs7O3AqBh()w0PNtJ2WAfN4Ce/RW0AkP{}Dpfk4uqd5wvE][R5l9RNZnDjIhN1+/4dfmF1PMeFPaqhEcH3vf4SzJcfd6P4g=="
	_, err := ParseLicense(serial, vmpPublic, vmpModulus, vmpProductCode, vmpBits)
	if err == nil {
		t.Fatal("The input has some unsupported characters that must be ignored. The input must be valid, but the serial number itself - doesn't")
	}
}
